version: '3'
volumes: 
  dados:
networks: 
  database:
  web:
  net_queue:
services:
  db:
    image: postgres:9.6
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes: 
      # Volume dos Dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - database
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Reverse proxy Nginx Configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
  app:
    image: python:3.6
    volumes:
      # Application
      - ./app:/app 
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080
    networks: 
      - database
      - web
      - net_queue
    depends_on: 
      - db
      - queue
    environment: 
      - DB_NAME=email_sender
  queue:
    image: redis:3.2
    networks: 
      - net_queue
  worker:
    build: workers
    volumes: 
      # Workers
      - ./workers:/workers/
    working_dir: /workers
    command: ./worker.py
    networks: 
      - net_queue
    depends_on: 
      - queue
